### ISSUE TITLE
when you write the word green, an error appears.

### ISSUE THREAD

**Issue by usmonzo** [zhao-stanley/chroma-ai#1]
<img width="1509" alt="изображение" src="https://github.com/zhao-stanley/chroma-ai/assets/104492848/bc76fa2b-c095-4047-996a-6a8698666013">

**Comment by zhao-stanley** [comment]
Can't seem to reproduce it on my end, can you provide the steps to reproduce this error and show a screenshot of the console?

**Comment by usmonzo** [comment]
<img width="1512" alt="изображение" src="https://github.com/zhao-stanley/chroma-ai/assets/104492848/c9fd23f6-637c-4c2e-9d4a-9de28ef89fa1">

**Comment by zhao-stanley** [comment]
Tweaked the prompt to try and fix that, let me know if the issue still persists.
